warning when migratepages is not installed

diff --git a/cases/page_migration/config b/cases/page_migration/config
--- a/cases/page_migration/config
+++ b/cases/page_migration/config
@@ -1,4 +1,4 @@
 if ! which migratepages > /dev/null ; then
-	echo "migratepages command not found" >&2
+	echo "migratepages command not found, you need install numactl." >&2
 	return 1
 fi
